# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "uas" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."boocrypt".device = "/dev/disk/by-uuid/fcd33135-2192-4840-95f6-81b41e1ace1a";


  fileSystems."/" =
    { device = "/dev/mapper/boocrypt";
      fsType = "tmpfs";
      neededForBoot = true;
      # options = [ "subvol=root" ];
    };

  fileSystems."/data" =
    { device = "/dev/mapper/boocrypt";
      fsType = "btrfs";
      neededForBoot = true;
      options = [ "subvol=root" ];
    };


  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C191-6F86";
      fsType = "vfat";
    };

  fileSystems."/cfg" =
    { device = "/dev/mapper/boocrypt";
      fsType = "btrfs";
      options = [ "subvol=config" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/boocrypt";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/boocrypt";
      fsType = "btrfs";
      neededForBoot = true;
      options = [ "subvol=store" ];
    };

  fileSystems."/swap" =
    { device = "/dev/mapper/boocrypt";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
