# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/098447a4-05ce-4e74-a77b-2378489bc4ba";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7F97-23EB";
      fsType = "vfat";
    };

  fileSystems."/cfg" =
    { device = "/dev/disk/by-uuid/098447a4-05ce-4e74-a77b-2378489bc4ba";
      fsType = "btrfs";
      options = [ "subvol=config" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/098447a4-05ce-4e74-a77b-2378489bc4ba";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/098447a4-05ce-4e74-a77b-2378489bc4ba";
      fsType = "btrfs";
      options = [ "subvol=store" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/098447a4-05ce-4e74-a77b-2378489bc4ba";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
